name: validator
description: This app is to display the Validator details

version: 1.1.1+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+4
  intl: ">=0.14.0"
  material_segmented_control: ^2.0.11+1
  flutter_spinkit: ^4.1.2+1
  charts_flutter: ^0.9.0
  shared_preferences: ^0.4.3
  webview_flutter: ^0.3.20+2
  rflutter_alert: ^1.0.3
  barcode_scan: any
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.13
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  flutter_local_notifications: ^1.4.3
  sqflite: ^1.3.0+1
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - assets/

